package com.emergency.backend.service;

import com.emergency.backend.entity.Incident;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.io.image.ImageDataFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.File;

/**
 * Service for generating PDF reports of incidents.
 * Uses iText 7 library to create professional PDF documents
 * with incident details and images.
 */
@Service
public class PdfExportService {

    @Value("${file.upload-dir:${user.dir}/uploads}")
    private String uploadDir;

    /**
     * Generate a PDF report for a single incident.
     * Includes title, category, description, location, status,
     * reported date, and embedded incident image.
     */
    public byte[] generateIncidentReport(Incident incident) throws Exception {

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        try (PdfWriter writer = new PdfWriter(outputStream);
             PdfDocument pdf = new PdfDocument(writer);
             Document document = new Document(pdf)) {

            // Title
            document.add(new Paragraph("EMERGENCY INCIDENT REPORT")
                    .setFontSize(24)
                    .setBold()
                    .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER));

            document.add(new Paragraph("─".repeat(50))
                    .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER));

            // Incident Details Table
            Table table = new Table(UnitValue.createPercentArray(2)).useAllAvailableWidth();

            addTableRow(table, "Report ID", String.valueOf(incident.getId()));
            addTableRow(table, "Title", incident.getTitle() != null ? incident.getTitle() : "N/A");
            addTableRow(table, "Category", incident.getCategory() != null ? incident.getCategory() : "N/A");
            addTableRow(table, "Status", incident.getStatus() != null ? incident.getStatus() : "N/A");
            addTableRow(table, "Location", incident.getLocation() != null ? incident.getLocation() : "N/A");
            addTableRow(table, "Reported By", incident.getUserEmail() != null ? incident.getUserEmail() : "N/A");
            addTableRow(table, "Description", incident.getDescription() != null ? incident.getDescription() : "N/A");
            addTableRow(table, "Date Reported",
                    incident.getCreatedAt() != null ? incident.getCreatedAt().toString() : "N/A");

            document.add(table);

            // Add Image if available
            if (incident.getImage() != null && !incident.getImage().isEmpty()) {
                String imagePath = uploadDir + File.separator + incident.getImage();
                File imageFile = new File(imagePath);

                if (imageFile.exists()) {
                    document.add(new Paragraph("\n\nIncident Image:"));
                    Image img = new Image(ImageDataFactory.create(imagePath));
                    img.setWidth(UnitValue.createPercentValue(80));
                    img.setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
                    document.add(img);
                }
            }

            // Footer
            document.add(new Paragraph("\n\n"));
            document.add(new Paragraph("─".repeat(50))
                    .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER));
            document.add(new Paragraph(
                    "Generated by Emergency Alert System | " +
                    new java.text.SimpleDateFormat("dd-MM-yyyy HH:mm")
                            .format(new java.util.Date()))
                    .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER)
                    .setFontSize(10));
        }

        return outputStream.toByteArray();
    }

    /**
     * Helper to add a row to the details table.
     */
    private void addTableRow(Table table, String key, String value) {
        table.addCell(new Paragraph(key).setBold().setFontSize(11));
        table.addCell(new Paragraph(value != null ? value : "N/A").setFontSize(11));
    }
}

